### ISSUE TITLE
mongoreplay | libpcap

### ISSUE THREAD

**Issue by nehaljwani** [conda-forge/mongo-tools-feedstock#4]
We do have https://github.com/conda-forge/libpcap-feedstock . Why was mongoreplay skipped? 🤔

**Comment by sodre** [comment]
I was having issues getting go to find pcap.h or finding the library to link against. 

I read the `cgo` [documentation](https://golang.org/cmd/cgo/#hdr-Using_cgo_with_the_go_command) in more detail and found that I needed to make some additional modifications to the build.sh script. This is now taken care in the referenced PR.
