### ISSUE TITLE
Put back onto releases

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/mongo-tools-feedstock#9]
Would it be possible to put this back on a standard tarball?
@conda-forge/mongo-tools

**Comment by sodre** [comment]
I’m happy to make the changes you need but:

1. I’m away w/o my computer for the rest of the week. 
2. I’m not what what you meant as far as releases.

**Comment by CJ-Wright** [comment]
I mean back on to tarballs (rather than git repos)

**Comment by sodre** [comment]
Generally, It is not always easy for go packages to be built back from tar balls. A lot of times the build scripts embed the git commit/tag in the final binary, which the tarballs do not contain. 

In the past I would create an ugly hack to git init SRCDIR, but that meant the commit hash dit not match upstream and other problems. 

I usually don’t use the git alternative unless necessary, but I’ll double check for mongo tools.

**Comment by CJ-Wright** [comment]
hmm ok. I mostly ask because it was built on a tarball in the past and because the autotick bot doesn't do git urls.

**Comment by nehaljwani** [comment]
https://github.com/mongodb/mongo-tools/blob/r4.1.8/set_goenv.sh#L84-L89

**Comment by nehaljwani** [comment]
Can the autotick bot be taught to look at github tags? Maybe we can have a field in the 'extra' section in the recipe to force tell the auto tick bot what to look for, in the original source?

**Comment by CJ-Wright** [comment]
The bot does look at Github releases, but usually when a github tarball is used.
PRs are welcome for supporting git_urls.

**Comment by sodre** [comment]
I moved the recipe to use the tarballs.
